module.exports = {
  apps: [
    {
      name: 'scholars-tea',
      script: 'node_modules/next/dist/bin/next',
      args: 'start -p 3002',
      cwd: '/data/home/zju321/scholars-tea',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        DATABASE_URL: 'postgresql://zju321@127.0.0.1:5432/scholars_tea',
        REDIS_URL: 'redis://localhost:6379',
        NEXTAUTH_SECRET: 'your-secret-change-in-production',
        NEXTAUTH_URL: 'http://localhost:3002',
        HTTP_PROXY: '',
        HTTPS_PROXY: '',
        http_proxy: '',
        https_proxy: '',
        NO_PROXY: '',
      },
    },
    {
      name: 'scholars-tea-socket',
      script: 'server/dist/index.js',
      cwd: '/data/home/zju321/scholars-tea',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      env: {
        NODE_ENV: 'production',
        DATABASE_URL: 'postgresql://zju321@127.0.0.1:5432/scholars_tea',
        NEXTAUTH_SECRET: 'your-secret-change-in-production',
        SOCKET_PORT: '3001',
        HTTP_PROXY: '',
        HTTPS_PROXY: '',
        http_proxy: '',
        https_proxy: '',
        NO_PROXY: '',
      },
    },
  ],
}

